# Generated by Django 5.1.4 on 2025-01-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
